name = input ("Hey, what's your first name? : ")
nameclean = name.strip()
lastname = input ("and your last name? : ")
lastname = lastname.strip()
print ("Well, pleased to meet you,", nameclean, lastname)
